### ISSUE TITLE
Retrieve session by id

### ISSUE THREAD

**Issue by spoptchev** [redis-store/redis-store#129]
Sorry, to bother you with a question, but I just can't find a good solution:

How can I retrieve the session by id from redis?

I'm looking for something like `ActiveRecord::SessionStore::SqlBypass.find(123456789)`

**Comment by Zogoo** [comment]
Just in case someone is searching for the answer to the same question.
```rb
redis_session_key = "YOUR-NAME-SPACE::#{Digest::SHA256.hexdigest(session.id.to_s)}"
Redis.new(url: "REDIS-URL").get(redis_session_key)
```
