### ISSUE TITLE
Does Redis-store support :size parameter for redis-rails cache?

### ISSUE THREAD

**Issue by hrdwdmrbl** [redis-store/redis-store#153]
For example, from the Rails Guide on caching:

```
config.cache_store = :redis_store, :size => 64.megabytes
```

or

```
config.cache_store = :redis_store, {host: 'localhost', port: 6379, :size => 64.megabytes
```

It isn't mentioned anywhere, but it should be part of any rails cache store implementation. So, I just wanted to make sure. Thanks.

**Comment by girishhh** [comment]
can any one tell me what is max storage limit of redis cache
