### ISSUE TITLE
Namespace doesn't support expire method

### ISSUE THREAD

**Issue by rajatvig** [redis-store/redis-store#154]
Thus all such calls go the parent Redis which returns false as there's no such key.

Refer to commit https://github.com/rajatvig/redis-store/commit/6b929b847851c8ca699c2e6ba40877aeb566a66b

**Comment by fenelon** [comment]
I've been battling with this all night! Please fix!

**Comment by radar** [comment]
My PayPal account is radarlistener@gmail.com.

Or you could investigate or patch this yourself?
