### ISSUE TITLE
How to view all redis sessions?

### ISSUE THREAD

**Issue by krzkrzkrz** [redis-store/redis-store#162]
Ive set up session_store to use redis_store. Typing `$redis.keys` in the console doesn't show my the session_store keys. Any ideas why?

**Comment by nofxx** [comment]
Just to the annals of "How to view all redis sessions?"

Use same config as app:

```
r = Redis.new Rails.application.config.session_options[:servers]
r.keys 
#=> [All session keys keys, ....]
```

Get a user out supposing devise & warden & marshal. 

```
u = User.find Marshal.load(r.get("mind-yr-namespaces:#{key}")).values.flatten.first
# or
u = User.find Marshal.load(r.get("mind-yr-namespaces:#{key}"))['warden...'][0][0]
```
