### ISSUE TITLE
Uninitialized Constant Rack::Session::Redis

### ISSUE THREAD

**Issue by kingbari** [redis-store/redis-store#176]
I'm using sinatra version 1.4.2 with redis-store 1.1.3 and I'm experiencing the following error
```app.rb:34 - uninitialized constant Rack::Session::Redis```

when I:

```
require 'redis-store'
use Rack::Session::Redis, :redis_server => 'redis://127.0.0.1:6379/0'
```

Since sinatra version 1.4.2 depends on rack ~> 1.5 I'm unable to install redis-rack which depends on rack ~> 1.4

How can/should I resolve this issue?

**Comment by tubbo** [comment]
`Rack::Session::Redis` is part of the redis-store/redis-rack gem. https://github.com/redis-store/redis-rack/blob/master/lib/rack/session/redis.rb
