### ISSUE TITLE
TypeError Redis is not a module

### ISSUE THREAD

**Issue by blanchma** [redis-store/redis-store#180]
I saw I'm not the first one with this error but I didn't find a solution there. And redis-activesupport is in 0.0.0. 

My gemfile is:

source 'http://rubygems.org'

gem 'rails', '3.0.18'
gem 'rack', '1.2.5'
gem 'jquery-rails'
gem 'aws-sdk'
gem 'rest-client'
gem 'aes'
gem 'httparty', '0.8.3'
gem 'settingslogic'
gem 'newrelic_rpm'
gem 'uuidtools'
gem 'thin'
gem 'acts_as_api'
gem 'exception_notification', git: 'git://github.com/alanjds/exception_notification.git'
gem 'mysql2','<0.3'
gem 'sidekiq'
gem 'whenever', :require => false
gem 'typhoeus'
gem 'attr_encrypted'
gem 'kaminari'
gem 'aylauth', path: "~/workspace/aylauth"
gem 'redis-activesupport'

  specs:
    abstract (1.0.0)
    actionmailer (3.0.18)
      actionpack (= 3.0.18)
      mail (~> 2.2.19)
    actionpack (3.0.18)
      activemodel (= 3.0.18)
      activesupport (= 3.0.18)
      builder (~> 2.1.2)
      erubis (~> 2.6.6)
      i18n (~> 0.5.0)
      rack (~> 1.2.5)
      rack-mount (~> 0.6.14)
      rack-test (~> 0.5.7)
      tzinfo (~> 0.3.23)
    activemodel (3.0.18)
      activesupport (= 3.0.18)
      builder (~> 2.1.2)
      i18n (~> 0.5.0)
    activerecord (3.0.18)
      activemodel (= 3.0.18)
      activesupport (= 3.0.18)
      arel (~> 2.0.10)
      tzinfo (~> 0.3.23)
    activeresource (3.0.18)
      activemodel (= 3.0.18)
      activesupport (= 3.0.18)
    activesupport (3.0.18)
    acts_as_api (0.4.1)
      activemodel (>= 3.0.0)
      activesupport (>= 3.0.0)
      rack (>= 1.1.0)
    addressable (2.3.2)
    aes (0.5.0)
    annotate (2.4.0)
    arel (2.0.10)
    attr_encrypted (1.2.1)
      encryptor (>= 1.1.1)
    aws-sdk (1.9.1)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
      uuidtools (~> 2.1)
    builder (2.1.2)
    capistrano (2.13.5)
      highline
      net-scp (>= 1.0.0)
      net-sftp (>= 2.0.0)
      net-ssh (>= 2.0.14)
      net-ssh-gateway (>= 1.1.0)
    celluloid (0.12.4)
      facter (>= 1.6.12)
      timers (>= 1.0.0)
    childprocess (0.3.6)
      ffi (~> 1.0, >= 1.0.6)
    choice (0.1.6)
    chronic (0.9.1)
    coderay (1.0.8)
    colored (1.2)
    columnize (0.3.6)
    connection_pool (1.0.0)
    crack (0.3.2)
    daemons (1.1.9)
    database_cleaner (0.9.1)
    debugger (1.2.2)
      columnize (>= 0.3.1)
      debugger-linecache (~> 1.1.1)
      debugger-ruby_core_source (~> 1.1.5)
    debugger-linecache (1.1.2)
      debugger-ruby_core_source (>= 1.1.1)
    debugger-ruby_core_source (1.1.5)
    diff-lcs (1.1.3)
    encryptor (1.1.3)
    erubis (2.6.6)
      abstract (>= 1.0.0)
    ethon (0.5.11)
      ffi (>= 1.3.0)
      mime-types (~> 1.18)
    eventmachine (1.0.0)
    facter (1.6.17)
    factory_girl (4.1.0)
      activesupport (>= 3.0.0)
    faraday (0.8.4)
      multipart-post (~> 1.1)
    faraday_middleware (0.9.0)
      faraday (>= 0.7.4, < 0.9)
    ffi (1.7.0)
    guard (1.5.4)
      listen (>= 0.4.2)
      lumberjack (>= 1.0.2)
      pry (>= 0.9.10)
      thor (>= 0.14.6)
    guard-rspec (1.2.1)
      guard (>= 1.1)
    guard-spork (1.4.0)
      childprocess (>= 0.2.3)
      guard (>= 1.1)
      spork (>= 0.8.4)
    hashie (1.2.0)
    highline (1.6.15)
    http_parser.rb (0.5.3)
    httparty (0.8.3)
      multi_json (~> 1.0)
      multi_xml
    i18n (0.5.0)
    jquery-rails (2.1.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.7.7)
    json_spec (1.1.0)
      multi_json (~> 1.0)
      rspec (~> 2.0)
    kaminari (0.14.1)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    listen (0.6.0)
    lumberjack (1.0.2)
    mail (2.2.19)
      activesupport (>= 2.3.6)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    metaclass (0.0.1)
    method_source (0.8.1)
    mime-types (1.22)
    mocha (0.12.7)
      metaclass (~> 0.0.1)
    multi_json (1.7.2)
    multi_xml (0.5.3)
    multipart-post (1.1.5)
    mysql2 (0.2.18)
    net-scp (1.0.4)
      net-ssh (>= 1.99.1)
    net-sftp (2.0.5)
      net-ssh (>= 2.0.9)
    net-ssh (2.6.2)
    net-ssh-gateway (1.1.0)
      net-ssh (>= 1.99.1)
    newrelic_rpm (3.5.3.25)
    nokogiri (1.5.9)
    permit (1.0.0)
    polyglot (0.3.3)
    pry (0.9.10)
      coderay (~> 1.0.5)
      method_source (~> 0.8)
      slop (~> 3.3.1)
    pry-remote (0.1.6)
      pry (~> 0.9)
      slop (~> 3.0)
    rack (1.2.5)
    rack-mount (0.6.14)
      rack (>= 1.0.0)
    rack-test (0.5.7)
      rack (>= 1.0)
    rails (3.0.18)
      actionmailer (= 3.0.18)
      actionpack (= 3.0.18)
      activerecord (= 3.0.18)
      activeresource (= 3.0.18)
      activesupport (= 3.0.18)
      bundler (~> 1.0)
      railties (= 3.0.18)
    rails-erd (1.0.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      choice (~> 0.1.6)
      ruby-graphviz (~> 1.0.4)
    railties (3.0.18)
      actionpack (= 3.0.18)
      activesupport (= 3.0.18)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (~> 0.14.4)
    rake (10.0.3)
    random_data (1.6.0)
    rdoc (3.12)
      json (~> 1.4)
    redis (3.0.3)
    redis-activesupport (0.0.0)
    redis-namespace (1.2.1)
      redis (~> 3.0.0)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rspec (2.6.0)
      rspec-core (~> 2.6.0)
      rspec-expectations (~> 2.6.0)
      rspec-mocks (~> 2.6.0)
    rspec-core (2.6.4)
    rspec-expectations (2.6.0)
      diff-lcs (~> 1.1.2)
    rspec-mocks (2.6.0)
    rspec-rails (2.6.1)
      actionpack (~> 3.0)
      activesupport (~> 3.0)
      railties (~> 3.0)
      rspec (~> 2.6.0)
    rspec-rails-mocha (0.3.2)
      mocha (>= 0.9.8)
      rspec-rails (>= 2.0.0)
    ruby-graphviz (1.0.8)
    ruby_parser (3.1.0)
      sexp_processor (~> 4.1)
    rvm-capistrano (1.2.7)
      capistrano (>= 2.0.0)
    seed_dumper (0.1.3)
      rails
    settingslogic (2.0.9)
    sexp_processor (4.1.3)
    sidekiq (2.7.5)
      celluloid (~> 0.12.0)
      connection_pool (~> 1.0)
      multi_json (~> 1)
      redis (~> 3)
      redis-namespace
    simple_oauth (0.1.9)
    simplecov (0.7.1)
      multi_json (~> 1.0)
      simplecov-html (~> 0.7.1)
    simplecov-html (0.7.1)
    slop (3.3.3)
    spork (1.0.0rc3)
    spork-rails (3.2.1)
      rails (>= 3.0.0, < 3.3.0)
      spork (>= 1.0rc0)
    test_xml (0.1.2)
      nokogiri (>= 1.3.2)
    thin (1.5.0)
      daemons (>= 1.0.9)
      eventmachine (>= 0.12.6)
      rack (>= 1.0.0)
    thor (0.14.6)
    timers (1.1.0)
    tinder (1.9.1)
      eventmachine (>= 0.12.0, < 2)
      faraday (~> 0.8)
      faraday_middleware (~> 0.8)
      hashie (~> 1.0)
      json (~> 1.6)
      mime-types (~> 1.16)
      multi_json (~> 1.0)
      multipart-post (~> 1.1)
      twitter-stream (~> 0.1)
    tomdoc (0.2.5)
      colored
      ruby_parser (>= 2.0.4)
    treetop (1.4.12)
      polyglot
      polyglot (>= 0.3.1)
    twitter-stream (0.1.16)
      eventmachine (>= 0.12.8)
      http_parser.rb (~> 0.5.1)
      simple_oauth (~> 0.1.4)
    typhoeus (0.6.3)
      ethon (~> 0.5.11)
    tzinfo (0.3.35)
    uuidtools (2.1.3)
    vcr (2.3.0)
    webmock (1.9.0)
      addressable (>= 2.2.7)
      crack (>= 0.1.7)
    whenever (0.8.2)
      activesupport (>= 2.3.4)
      chronic (>= 0.6.3)

**Comment by tubbo** [comment]
You don't seem to be loading redis-rails, just redis-active-support. Also, this definitely has more to do with your environment than it does with redis-store. Closing, unless anyone else sees this.

**Comment by masonforest** [comment]
If you are running into this issue on Rails 5.2 or greater you may be looking for  the [redis-actionpack](https://github.com/redis-store/redis-actionpack) gem for session management or [redis-rack-cache](https://github.com/redis-store/redis-rack-cache) for HTTP cache storage.

From the [redis-rails documentation](https://github.com/redis-store/redis-rails?tab=readme-ov-file#a-quick-note-about-rails-52):

> Rails 5.2.0 https://github.com/rails/rails/pull/31134, so you don't really need this gem anymore if you just need to store the fragment cache in Redis. Maintenance on the [redis-activesupport](https://github.com/redis-store/redis-activesupport) gem will continue for security and compatibility issues, but we are no longer accepting new features. We are still actively maintaining all other gems in the redis-store family, such as [redis-actionpack](https://github.com/redis-store/redis-actionpack) for session management, and [redis-rack-cache](https://github.com/redis-store/redis-rack-cache) for HTTP cache storage.
