### ISSUE TITLE
Performance bug in delete_matched

### ISSUE THREAD

**Issue by bpo** [redis-store/redis-store#186]
`delete_matched` in redis-store uses Redis's notorious "KEYS" command[1], which has extremely poor performance in Redis databases that have a lot of keys[2] - the KEYS command is O(N) over the keys in the database (*not* over the subset of keys to be matched). KEYS can block the database for anywhere from 200ms for an average Redis DB to up to 2s for a 3-4GB system.

I'm creating this issue just for explanatory purposes in case anyone notices poor performance while using redis-store, and I've added a patch that adds the same note to the code. I don't think there's anything else that needs to be done now.

A long-term solution if `delete_matched` performance is a consistent problem for anyone, would be to add code to Redis-store that maintains an index of the cache keys so that matching can be done faster - a tree-based search structure based on Redis hashes might be a good fit.

[1] https://github.com/jodosha/redis-store/blob/master/redis-activesupport/lib/active_support/cache/redis_store.rb#L48
[2] http://redis.io/commands/keys

**Comment by lvangool** [comment]
Hey folks, apologies for ressurecting this - any reason we can not switch out "keys" with "scan_each(....).to_a". I understand the count size could be different - but I guess that could be an optional argument to initialization with a sensible default?  

For my use-case I have a domain object chain where the parents have a "status" based on a calculation of its children's "status" etc. To avoid calculating each time I cache the value, then if *anyone* changes status I invalidate the whole cache tree for that domain object. To do that I need to use delete_matched.

**Comment by bpo** [comment]
@lvangool it looks like `delete_matched` (the subject of this issue) [was removed](https://github.com/redis-store/redis-store/compare/v1.1.4...v1.1.5)

A scan-based implementation would be more appropriate than the old keys-based one, but for the use case you're specifying you might also consider storing your cache trees as Redis hashes which can be deleted with a single deterministic call.

**Comment by tubbo** [comment]
We had some issues with this feature in the past on small datasets. The truth is, we can’t predict how big your redis db will be and thus I think it’s better to keep the current implementation and drop down to the redis.rb API, which is provided through Redis::Store since it inherits from Redis.
