### ISSUE TITLE
Rack::Cache cache error: Unknown storage provider

### ISSUE THREAD

**Issue by disbelief** [redis-store/redis-store#188]
Hi there,

I recently attempted to start using redis-store as a back end for the Rack::Cache HTTP caching of my Rails 3.2 app. However I'm seeing the following stacktrace after following the README instructions:

```
cache error: Unknown storage provider: redis://REDACTED_REDIS_HOST:6379/1/metastore
ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/storage.rb:39:in `create_store'
ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/storage.rb:18:in `resolve_metastore_uri'
ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:34:in `metastore'
ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:169:in `lookup'
ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
ruby/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb:479:in `call'
ruby/1.9.1/gems/railties-3.2.13/lib/rails/application.rb:223:in `call'
ruby/1.9.1/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
```

I can confirm that redis-store is working for my fragment caches, and that the same URL is being used for that connection.

Here are the relevant lines from my environment file:
```ruby
# config/environments/production.rb

config.cache_store = :redis_store, "redis://REDACTED_REDIS_HOST:6379/1", { expires_in: 120.minutes }

config.action_dispatch.rack_cache = {
  metastore:   "redis://REDACTED_REDIS_HOST:6379/1/metastore",
  entitystore: "file:/tmp/cache/entitystore"
}

```

Should this work, or have I missed something from the readme?

**Comment by mmahalwy** [comment]
any update on this?

**Comment by radar** [comment]
If there was it would be posted here.

**Comment by tubbo** [comment]
@Ingary your configuration is somewhat strange...it should be `:metastore`, not `:MetaStore`.

**Comment by CaioBianchi** [comment]
I'm still experiencing the same issue with the `:metastore` provider.

**Comment by tubbo** [comment]
@CaioBianchi @jfloff what version is installed (`cat Gemfile.lock | grep redis-store`)? also, can you paste your rack-cache config?

**Comment by helmiattastify** [comment]
@tubbo 

config.action_dispatch.rack_cache = {
    metastore: "redis://localhost:6379/1",
    entitystore: "redis://localhost:6379/1",
    verbose: true,
    compress: true
    # NOTE: `:meta_store` and `:entity_store` are also supported.
  }

cache: [GET /api/users] miss

**Comment by jfloff** [comment]
I just got this error again 😅 . I have the latest version `1.10.0` installed and I'm running on Rails 6.

My configuration looks like this:
```ruby
rack_cache = {
    metastore: ::Rack::Cache::MetaStore::Redis.new("#{ENV['REDIS_TLS_URL']}/1/metastore", ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }),
    entitystore: ::Rack::Cache::EntityStore::Redis.new("#{ENV['REDIS_TLS_URL']}/1/entitystore", ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }),
  }
```

**Comment by radar** [comment]
@jfloff would you mind opening a new issue, as this one is quite old? And please show us how that rack_cache variable is being used.
