### ISSUE TITLE
Is there any mechanism in place for ActiveSupport to prevent Cache Stampeding?

### ISSUE THREAD

**Issue by gotjosh** [redis-store/redis-store#199]
While reading on the documentation, there seems to be missing any information regarding Cache Stampeding and if something is actually done to prevent it. Perhaps we could gather more information to update the documentation or implement it.

**Comment by radar** [comment]
@gotjosh Would you be interested in writing some documentation for this?

**Comment by tubbo** [comment]
As far as I know there's no mechanism in place for this. I'd be happy to merge documentation regarding this, or look over pull requests with engineered solutions to the problem.
