### ISSUE TITLE
Reference to Redis::Factory instead of Redis::Store::Factory in redis-activesupport

### ISSUE THREAD

**Issue by pierre-pretorius** [redis-store/redis-store#210]
My Gemfile contains:

gem 'rails', '~> 3.2'
gem 'redis-rails'

This causes bundler to install:

redis-rails (3.2.3)
redis-activesupport (3.2.3)
redis-store (1.1.4)

There is a reference to Redis::Factory instead of Redis::Store::Factory in:
gems/redis-activesupport-3.2.3/lib/active_support/cache/redis_store.rb

Which throws:
redis-activesupport-3.2.3/lib/active_support/cache/redis_store.rb:27:in `initialize': uninitialized constant Redis::Factory (NameError)

Can you please update this reference or fix the dependencies?  For now I have locked my redis-store gem version to 1.1.3.

Thank you

**Comment by radar** [comment]
Hi all, what needs to be done here? Do we need a new release of `redis-activesupport` still? Is there anything else?
