### ISSUE TITLE
Using hash instead of string

### ISSUE THREAD

**Issue by nadavshatz** [redis-store/redis-store#222]
Considering the session itself is a hash, why not use the hash data type that redis has?
Making it easier to look into data in the redis-cli itself and a more accurate representation.

**Comment by radar** [comment]
@nadavshatz Could you please explain what you meant here?

**Comment by nadavshatz** [comment]
The session data is currently serialized/marshaled back and forth when going in and out of redis. But redis also has support for the hash type instead of just a string. So why not store the data in redis using this data type?

**Comment by radar** [comment]
Sounds good to me. Can you please submit a patch for this issue?

**Comment by tubbo** [comment]
@nadavshatz I like your idea, but since this has been out for more than a year and no work has been done, I'm going to close due to inactivity.

**Comment by nadavshatz** [comment]
Perfectly understandable, I was going to submit a PR for it but never got around to it.

**Comment by tubbo** [comment]
If you ever do, reference this issue so we have a full history :)

Anyone else willing to take on the work...be my guest!
