### ISSUE TITLE
Namespaces are not working for Lists, Sets, Hashes, ...

### ISSUE THREAD

**Issue by johvet** [redis-store/redis-store#224]
I just came across this problem:

    a = Redis::Store::Factory.create("redis://localhost:6379/0/my-ns")
    a.set "cool", "stuff"
    a.sadd "other", "things"
    a.lpush "getit", "done"
    a.hset "hashit", "name", "foo"

And then doing a 

    $ redis-cli keys "*"
    1) "my-ns:cool"
    2) "hashit"
    3) "other"
    4) "getit"

**Comment by radar** [comment]
If someone wants to submit a patch to fix this behaviour I would be happy to review it.
