### ISSUE TITLE
Bug? Why are the options not passed to super?

### ISSUE THREAD

**Issue by fruwe** [redis-store/redis-store#230]
I tried to use Redis::Store to access redis, but noticed that Redis::Store#set(key, value, options) does not pass the options hash to Redis#set(set, value, options). Is there a reason why? Or this a bug?

<pre>
@redis = Rails.cache.instance_variable_get(:@data)
@redis.set "test", "value", nx: true, ex: 7200 # => "OK"
@redis.set "test", "value", nx: true, ex: 7200 # => "OK" but should return nil
</pre>

A possible fix would be:

<pre>
class Redis
  class Store  self
    module Interface
      def set(key, value, options = nil)
        super(key, value, options)
      end
    end

    module Ttl
      def set(key, value, options = nil)
        if ttl = expires_in(options)
          setex(key, ttl.to_i, value, :raw => true)
        else
          super(key, value, options)
        end
      end
    end
  end
end
</pre>

**Comment by radar** [comment]
Hi @fruwe, could you please submit a patch to fix this issue?

**Comment by fruwe** [comment]
sure
