### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by Tonkpils** [redis-store/redis-store#234]
I was wondering what the status is on this gem if its being actively maintained or not? I see many issues opened without comments from last year along with most other gems included in https://github.com/redis-store/redis-rails

**Comment by pixelvitamina** [comment]
I also wonder whats currently the best option for a redis session store and rack/sinatra?

**Comment by xpepermint** [comment]
+1

**Comment by shaqq** [comment]
cc @jodosha

**Comment by radar** [comment]
I contacted [@jodosha on Twitter](https://twitter.com/ryanbigg/status/566069956467388416) and he said [he was no longer maintaining it](https://twitter.com/jodosha/status/566132201990156288). I said that I could take it over and so now I am the new maintainer of redis-store.
