### ISSUE TITLE
Doc Site 'redis-store.org' is down?

### ISSUE THREAD

**Issue by sci-phi** [redis-store/redis-store#248]
I am unable to access the documentation website at "http://redis-store.org/redis-rack/"

**Comment by radar** [comment]
Yes it would appear so. Please refer to the documentation in redis-store/redis-rack. If that's lacking any information, please let us know by filing an issue on that repo

**Comment by stevenpetryk** [comment]
What documentation?

**Comment by espen** [comment]
Gems are still referencing http://redis-store.org in the repo description.
