### ISSUE TITLE
NotImplementedError on expiring with Sidekiq.

### ISSUE THREAD

**Issue by MatUrbanski** [redis-store/redis-store#260]
Hi. I have the same issue like this one: #74. I have model  in my rails app that looks similar to this one:
```
class Schema < ActiveRecord::Base
  has_many :schema_items

  def self.from_cache(schema_id)
    schema = Rails.cache.read("schema_#{schema_id}")
    unless schema
      schema = Schema.where(id: schema_id).includes(:schema_items).first
      Rails.cache.write("schema_#{schema_id}", schema) if schema
    end
    schema
  end
end
``` 

I'm calling ```Schema.from_cache``` method in sidekiq worker. From time to time it raises ```NotImplementedError```. Any suggestions for solving this problem?

**Comment by tubbo** [comment]
That's quite strange, are you sure it was a `NotImplementedError` and not a `NoMethodError`? If it was the latter, I've had that kind of thing happen occasionally when deploying new code changes to a cluster of web app servers, but not deploying code changes to my worker servers. It causes the web app to add jobs to the workers for which a class cannot be established, and thus some kind of error is thrown.

**Comment by tubbo** [comment]
@MatUrbanski if this is still happening let me know, otherwise looks like this was fixed a few years ago. make sure you update your gems.
