### ISSUE TITLE
Update Travis url

### ISSUE THREAD

**Issue by n-rodriguez** [redis-store/redis-store#264]
In all redis-store projects, the Travis url is wrong in README file : 
Example : for redis-store it points to https://travis-ci.org/jodosha/redis-store?branch=master instead of https://travis-ci.org/redis-store/redis-store?branch=master

**Comment by tubbo** [comment]
You're right, we should definitely have build status badges on all our READMEs. I think some of them have that, but a lot of them don't. That status badge would link to the Travis CI build.

**Comment by tubbo** [comment]
@n-rodriguez This has been resolved, but for what its worth it would have been a real easy way to get your name on the contributors list for this gem had you submitted a pull request instead of an issue :)
