### ISSUE TITLE
Namespace should be a query string

### ISSUE THREAD

**Issue by brodock** [redis-store/redis-store#268]
I would like to discuss a change in the way Redis URI is interpreted. Please see the relevant part in the [Redis Protocol Specification](https://www.iana.org/assignments/uri-schemes/prov/redis): 

>   The "query" URI field is used to specify client-library-
>   implementation-specific connection parameters and is therefore not
>   portable.  Using it without knowledge of which specific client
>   library is going to be used ought to be avoided.
>   The meaning of "path" URI field values that do not conform to the
>   "db-number" grammar have no known meaning or usage.  Using such
>   values ought to be avoided.
>   If both a "db-number" value and a "query" URI field key-value pair
>   with the key "db" are present, the semantics for what Redis database
>   number to use are not well-defined.  Such situations therefore ought
>   to be avoided.
>   If both the password portion of the "userinfo" URI field and a
>   "query" URI field key-value pair with the key "password" are present,
>   the semantics for what password to use for authentication are not
>   well-defined.  Such situations therefore ought to be avoided.

Instead of a second level path we should use something in within the query string.
This is the proposed format:

```
redis://<username>:<password>@<host>:<port>/<db-num>?namespace=<namespace_string>
```

For backward compatibility we should support the old format : `/<db-num/<namespace_string>` but with a warning

**Comment by tubbo** [comment]
I understand the concern here, but is there any functional need to do this? Has anyone had situations where Redis namespace keys caused issues with authentication?

The issue I have with changing this is the amount of documentation, tutorials, and blog posts which reference the "old" syntax. Changing this and issuing a deprecation warning essentially invalidates all of that.

**Comment by brodock** [comment]
@tubbo My proposal was a result of a personal use-case, that while may not be relevant to everyone, I still believe that if every redis-related library follow the same standard we end-up typing less code.

We use redis-store, redis-rb and a few other redis-aware libraries, and maintaining a common "Redis URL" is today not possible. What we do is parse user provided URL, transform it back to a hash and build the URL again with the specificities of every library.

**Comment by tubbo** [comment]
@brodock I don't see why that format wouldn't work, honestly. Sure, we support /0/whatever-namespace, but only because Redis does. You can specify a URL String whenever you invoke redis-store, so I'm not sure what needs to be changed on our end in order to support what you want.

**Comment by tubbo** [comment]
@brodock I'm not sure why you can't just have the URL with the query string in it and call it a day. If it's a valid URL, and Redis interprets the `?namespace=` query param the same way it interprets `/:db/:namespace`, then I don't see why you can't do this right now.

Since I can't think of anything redis-store needs to do in order to get this working, I'm going to close the issue. Feel free to comment back and I'll reopen it if you think there's anything we can do to help  (other than changing documentation)
