### ISSUE TITLE
Test with redis-rb 4.0.1

### ISSUE THREAD

**Issue by djanowski** [redis-store/redis-store#277]
I just released redis-rb 4.0.0 RC1.

Can you please test against it and report back?

Thank you!

**Comment by tubbo** [comment]
Absolutely, thanks for letting us know.

**Comment by nanaya** [comment]
For what it's worth, with exception of tests related to `DistributedStore` (and removing all references to it), nothing else seems to be broken (as in the test passes).

**Comment by tubbo** [comment]
@nanaya what replaced the `Redis::Distributed` object? I had issues stemming from the library no longer including a 'redis/distributed' file.

**Comment by nanaya** [comment]
Apparently there's no replacement at the moment according to [this comment](https://github.com/redis/redis-rb/issues/650#issuecomment-263206710).

**Comment by tubbo** [comment]
That seems like a deal breaker to me. Until redis.rb announces a contingency plan, we can't really upgrade to 4. People definitely use `Redis::DistributedStore`, and removing that would be a breaking change. It would be really cool if we didn't have to release a breaking change in order to account for redis.rb's agenda.

**Comment by djanowski** [comment]
We backed off from removing Redis::Distributed. FYI redis-rb 4.0 with support for Redis::Distributed.

**Comment by tubbo** [comment]
@djanowski <3 <3 <3

**Comment by tubbo** [comment]
With v4.0.1 we can also test #282, so I'll wait until that's released until making a release here. But I think we're mostly compatible.

**Comment by shaneog** [comment]
> With v4.0.1 we can also test #282, so I'll wait until that's released until making a release here. But I think we're mostly compatible.

How's this coming along?

**Comment by tubbo** [comment]
@shaneog hey sorry for closing this, I'm about to release v4.0.1

**Comment by tubbo** [comment]
1.4.1 is released

**Comment by PikachuEXE** [comment]
Should we test with both redis 3 & 4?

**Comment by tubbo** [comment]
Might be a good use for Appraisals, as we're using that on other gems to
test against multiple Rails versions.

**Comment by PikachuEXE** [comment]
@tubbo 
#300 opened
