### ISSUE TITLE
Reconnecting the Cache Store

### ISSUE THREAD

**Issue by coding-bunny** [redis-store/redis-store#278]
Hello,

I'm currently tweaking our Rails Cache in Unicorn.
Because we use the same code base for both Sidekiq and Unicorn, we initialize the cache for Rails with a specific setting, but overwrite this in the initializers based on the environment.

According to #21 it should be possible to simply call `reconnect`, however this is not working.
At the moment I need to do this in our initializers:

```
[6] pry(main)> Rails.cache.data.shutdown(&:disconnect)
=> nil
[7] pry(main)> Rails.cache.reconnect
=> nil
[8] pry(main)> Rails.cache.read('*')
ConnectionPool::PoolShuttingDownError: ConnectionPool::PoolShuttingDownError
[9] pry(main)> ::Rails.configuration.cache_store = :redis_store, Chamber[:redis][:cache], { expires_in: 7.days.to_i, pool_size: ::Rails.configuration.default_sidekiq_connection_count, pool_timeout: 5 }  
=> [:redis_store, "redis://127.0.0.1:6379/1", {:expires_in=>604800, :pool_size=>7, :pool_timeout=>5}]
[10] pry(main)> ::Rails.cache = ::ActiveSupport::Cache.lookup_store(::Rails.configuration.cache_store)  
[11] pry(main)> Rails.cache.read('*')
=> nil
```

**Comment by tubbo** [comment]
At the end of the day, calling `Rails.cache.reconnect` just calls the `Redis#reconnect` method on the client instance for each node (if distributed) or on the single client instance if you're only using one server.

https://github.com/redis-store/redis-store/commit/3f0dcb32bcc307365ad4d96541c605516e126fe2#diff-34c032f583ec1c00c414f805c2ce0df9R16

Are you using the DistributedStore? It looks like you're using redis-store with connection_pool here.

**Comment by coding-bunny** [comment]
We are not using the DistributedStore.
We have a single Redis point in the application for the Rails.Cache and the Rails.configuration.redis which is used for stuff like semaphores and temporary storage.

We use however a ConnectionPool to allow more then one connection to it.

**Comment by tubbo** [comment]
Hmm, well we're just calling the `Redis#reconnect` method...this might just be latency in communicating with Redis itself, but the actual "meat & potatoes" of this functionality lies in redis.rb.

**Comment by coding-bunny** [comment]
I can run more tests, but wrapping it in the ConnectionPool doesn't reconnect the pool properly when calling reconnect for some reason.

Could it be that the ConnectionPool itself is not calling the proper method ?

**Comment by tubbo** [comment]
that's definitely possible. it seems to me that we're just delegating to the Redis client when calling reconnect, so I'm not sure what redis-store can do to resolve this issue.

**Comment by tubbo** [comment]
I'm gonna close this because it really seems like ConnectionPool is having problems reconnecting under the hood, and Redis::Store is behaving properly. If anyone can offer some counterpoint to that opinion, I'm all ears.

**Comment by coding-bunny** [comment]
no, I think that's a correct assement.
