### ISSUE TITLE
How do I use multiple redis urls for the cache_store ?

### ISSUE THREAD

**Issue by dorongutman** [redis-store/redis-store#285]
I'm using AWS ElastiCache redis cluster with 4 nodes - one primary and 3 replicas.
How do I configure more then one redis connection string in `config.cache_store` ?

**Comment by tubbo** [comment]
@dorongutman There are a couple different options. You could use `DistributedStore` which will activate automatically upon passing multiple addresses into the config.

```ruby
config.cache_store = ['redis://...', 'redis://...'];
```

This also works as an Array of Hashes.

Additionally, you could use Redis Sentinel and [follow the README](https://github.com/redis-store/redis-rails#usage-with-redis-sentinel) to set that up.

**Comment by tubbo** [comment]
@dorongutman did this answer your question? I'm gonna close it just so I know it's responded to, but feel free to comment or reopen if you're still having issues.
