### ISSUE TITLE
mention SemVer compliance in README

### ISSUE THREAD

**Issue by pravi** [redis-store/redis-store#287]
I assume you already follow SemVer.org (I can see redis-rails already using >= 1.2, < 2). It would be nice if you can mention this in README, so other dependencies can also relax their dependencies. redis-actionpack wants < 1.4.0, and redis-activesupport wants ~> 1.3.0.

This will ease my work in maintaining redis-store in debian. Many projects do this already https://wiki.debian.org/Teams/Ruby/UpstreamPledge

**Comment by tubbo** [comment]
thanks @pravi, we should probably update redis-activesupport to the same dependency constraints as redis-actionpack has. I'll run some tests to be sure it will be OK.

**Comment by tubbo** [comment]
@pravi I just updated the README to mention semver compliance. thanks for pointing this out!
