### ISSUE TITLE
TODO: Release a new version of redis-store

### ISSUE THREAD

**Issue by film42** [redis-store/redis-store#296]
Not trying to cause noise or annoyance, @tubbo . Just opening this issue so I can get notified when you cut the latest release of redis-store 😄 . Thanks for all your hard work ❤️ !

**Comment by tubbo** [comment]
Not at all, I appreciate it as it’s kinda hard to keep track of issues throughout all these different projects. Trying to figure out a good solution... :)

- T

**Comment by tubbo** [comment]
@film42 v1.4.1 is now on rubygems.
