### ISSUE TITLE
Support for hiredis

### ISSUE THREAD

**Issue by anurag90x** [redis-store/redis-store#303]
Does the library support using hiredis for connections? https://github.com/redis/hiredis-rb

From the spec (https://github.com/redis-store/redis-store/blob/master/redis-store.gemspec#L22) it looks like it only supports  https://github.com/redis/redis-rb.

**Comment by tubbo** [comment]
You are correct, this library depends on redis.rb and not hiredis. Because of the way it’s designed we can’t support the use of hiredis without a major version upgrade (breaking change). 

- T

**Comment by anurag90x** [comment]
Ok, thanks.
