### ISSUE TITLE
Use redis UNLINK instead of DEL

### ISSUE THREAD

**Issue by nightsurge** [redis-store/redis-store#311]
I've recently had some troubles with slowlog requests and most of the time they tend to relate to deleting large sums of data using the "DEL" command (or rather, using the redis-rails gem for cache_store and using the Rails.cache.delete 'some_key' method)

Since redis 4 it appears UNLINK is pretty much the go to choice and is much better performance wise by doing any actual data cleanup in a separate thread.

Could we either make the change globally or allow some config option to say which option to use?

**Comment by nightsurge** [comment]
Hmm, perhaps my usage is very edgecase. I implemented a workaround by using a global $redis instance alongside my Rails.cache so for these cases of "Rails.cache.delete" I can replace with $redis.unlink.

So maybe rather than changing DEL to UNLINK, just add UNLINK and then in the redis-rails code for Rails.cache.delete, check to see if "unlink" is a supported command. If supported, use "unlink", otherwise use "del".

**Comment by tubbo** [comment]
Seems legit to me. I don't think it would be terrible to make users update to redis.rb 4.0 if they want this feature, no need for the extra code to determine whether `Redis::Store` supports it or not.
