### ISSUE TITLE
Redis connection issue "No connection is available to service this operation"

### ISSUE THREAD

**Issue by KhalilKazi-gep** [redis-store/redis-store#325]
All of a sudden we were getting below issue on. 

No connection is available to service this operation: GET ([cahce key name]) :0:en-US; IOCP: (Busy=2,Free=32765,Min=800,Max=32767), WORKER: (Busy=2,Free=32765,Min=800,Max=32767), Local-CPU: n/a::: .

Redis version:  4.0.14

**Comment by tubbo** [comment]
I’m not sure this is a `Redis::Store` issue...are you looking for antirez/redis?
