### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by fonji** [redis-store/redis-store#335]
Hi!

As redis 4.2 is getting pushed through upgrade mechanisms, I think there is a need for https://github.com/redis-store/redis-store/pull/333 to be officially published.
I don't know the release mecanism, I don't think I should be the one pushing a PR changing `version.rb`, but that would be very nice.

Thanks for the great work, have a nice day!

**Comment by tubbo** [comment]
It wouldn’t matter anyway because you still can’t push to RubyGems :) I’ll release this today. Sorry for the delay. 

On Mon, Jun 22, 2020 at 8:26 AM GitHub <notifications@github.com> wrote:

“Assigned #335 to @tubbo.”

**Comment by fonji** [comment]
No worries! Thank you!

**Comment by tubbo** [comment]
redis-store 1.9 is out!
