### ISSUE TITLE
zremrangebyscore and other commands are not namespaced

### ISSUE THREAD

**Issue by skunkworker** [redis-store/redis-store#339]
I recently ran into a situation where I was calling `zadd` and then `zremrangebyscore` right after with the same key, but these two were not going to the same namespace.

```
redis.zadd("key", 1, "something")
redis.zremrangebyscore("key", 0, 2) => 0
```

Upon searching the repository I found that only `zadd` and `zrem` but not others were being namespaced. https://github.com/redis-store/redis-store/blob/master/lib/redis/store/namespace.rb#L153-L15 

I'm aware that the number of total commands is quite large, but would this be something that I could add and contribute to?

**Comment by tubbo** [comment]
I'm probably going to release a major version update in the future that gets rid of all that namespaced zaddwhateever method stuff. `Redis::Store` isn't supposed to be a client alternative to `Redis`, and with `Redis::Namespace` most of the use cases for using the same client are pretty much resolved. If `Redis::Namespace.new('your-namespace', redis: Redis.new(REDIS_URL))` can remove the need to maintain more code in this repo, that seems like the way to go...
