### ISSUE TITLE
How to disable renewing TTL when accessing the key?

### ISSUE THREAD

**Issue by dawidlenkiewicz** [redis-store/redis-store#341]
In the project I'm working on right now we use **redis_store** as a session store (Rails 6 app).

When adding expiration time for session we found out that everytime redis_store fetches the data from redis the key is auto-renewed and TTL i being reset to initial value.

Simple test is to open rails console, get the ttl value of given key, perform any action on the app so the session is used, get the ttl value once again.

```ruby
r.ttl("b7cafb90f60f79f90ef9014d48f8f09d")
before => 2591880
after => 2591998
```

This is confusing for me, what exactly causes the ttl to be reset? Is it default behaviour? If so is there a way to use the **KEEPTTL** option with Rails session maybe?

**Comment by tubbo** [comment]
What action are you performing in the app? Does it change (write to) the session? If so, that's [rewriting the value](https://github.com/redis-store/redis-rack/blob/master/lib/rack/session/redis.rb#L49) and [setting a new TTL on that key in Redis](https://github.com/redis-store/redis-store/blob/master/lib/redis/store/ttl.rb#L6) every time. Usually, when you change a value in Redis you want to reset the time at which it expires, and that behavior happens in both the cache store and the session store.

**Comment by dawidlenkiewicz** [comment]
@tubbo I'm not writing anything to the session, it's just about authentication - reading logged in user data.

Also I found out this issue https://github.com/redis-store/redis-rails/issues/35 which suggests this is an expected behaviour?

**Comment by tubbo** [comment]
I see what you mean. Yeah, this is expected behavior. The TTL value in a session store is supposed to be as long as you want sessions to be alive for. If you essentially want a "persistent" session that doesn't expire, at least very often, set it to `2.years` which I think is the max.

**Comment by arcreative** [comment]
@tubbo Is there no alternative to this?  We're not wanting to enforce idle/inactivity timeouts as much as enforcing a hard time limit on sessions to enforce a max session length on the server side.  I understand that writing a new key requires the TTL to be updated, but as @dawidlenkiewicz mentioned, we're not actually updating anything when we simply access the session.  

Any workaround would require heavy monkeypatching of other libraries, when it seems like this gem is the source of the unwanted behavior. Ideas?
