### ISSUE TITLE
Rails 6 compatibility? 

### ISSUE THREAD

**Issue by danlo** [redis-store/redis-store#342]
Greetings,

I've been trying to get the redis sessions to work with Rails 6.

Has this code been updated to work with Rails 6?  A fresh bare bones rails project, and I can set new values.

However:

https://github.com/redis-store/redis-actionpack/blob/master/lib/action_dispatch/middleware/session/redis_store.rb#L32

This is never called...

-daniel

**Comment by tubbo** [comment]
As far as I know, this gem does work with Rails 6. Can you show me what you’re trying to do?
  
  

  
  
>

**Comment by danlo** [comment]
Thank you!

I've created this public github repo:  https://github.com/lawgives/argh   *1  and Installed a minimal setup.

The files, I modified are: 

```
https://github.com/lawgives/argh/blob/main/config/initializers/session_store.rb (Initalize session store & modified to make get_cookie show if called)
https://github.com/lawgives/argh/blob/main/config/routes.rb (Need a route for controller)
https://github.com/lawgives/argh/blob/main/app/controllers/session_controller.rb (Testing)
https://github.com/lawgives/argh/blob/main/config/application.rb#L26 (hosts.clear)
```

When run the session is never loaded, although successfully set

Rails output:
```
user1_session=9674cc47a38b9bdd5adb56b92c90bea5
session.loaded?=false
Before: session[:testing]=
After: session[:testing]=2021-02-08 19:28:36 +0000
```

I can see this key in redis, so I know it was set properly.

```
1) "2::23d613f35d66e1ddc5d172d382edf027237063e1506e5f50923c7285549f26ab"
127.0.0.1:6379[4]> get "2::23d613f35d66e1ddc5d172d382edf027237063e1506e5f50923c7285549f26ab"
"\x04\b{\x06I\"\x0ctesting\x06:\x06EFI\"\x1e2021-02-08 19:28:36 +0000\x06;\x00F"
```

As when I modified the session store in "config/session_store", I put put statements to see when the cookie set and "gotten".  The "flag" for seeing the cookie being retrieved was never "obtained".

```
Started GET "/session/index" for 24.6.30.102 at 2021-02-08 19:29:53 +0000
Processing by SessionController#index as HTML
  Rendering text template
  Rendered text template (Duration: 0.0ms | Allocations: 2)
Completed 200 OK in 1ms (Views: 0.3ms | Allocations: 191)


SETCOOKIE: SETCOOKIE: SETCOOKIE: SETCOOKIE:  #<Rack::Response::Raw:0x000055fe3c2a15d0>
127.0.0.1 - - [08/Feb/2021:19:29:53 UTC] "GET /session/index HTTP/1.0" 200 147
- -> /session/index
127.0.0.1 - - [08/Feb/2021:19:29:53 UTC] "GET /favicon.ico HTTP/1.0" 200 0
```


*1:  
```
rails new login --skip-git --skip-keeps --skip-action-mailer --skip-action-mailbox --skip-action-text --skip-active-record --skip-active-job --skip-active-storage --skip-puma --skip-action-cable --skip-sprockets --skip-spring --skip-listen --skip-javascript --skip-turbolinks --skip-jbuilder --skip-webpack-install --skip-test --skip-system-test
```

**Comment by danlo** [comment]
@tubbo Is there anything I can do to help move this along?  Could I create a machine for you to test this out on easily?  I would need a public ssh key

**Comment by danlo** [comment]
Resolved, will file another bug report, had issues with ```config.session_store ... signed: true```  once I write up a good test case

**Comment by tubbo** [comment]
Ahh thanks @danlo I've noticed some others have had problems with that. Think there might be a discrepancy with how Rails 6 `signed: true` works vs the whole point of storing stuff in a centralized session store. In short, you probably don't want to use a centralized store if you're going to be signing and encrypting sessions, because a.) you don't need to, and b.) I don't know if it's possible.

**Comment by danlo** [comment]
@tubbo The documentation example suggests using signed.

```
https://github.com/redis-store/redis-actionpack/blob/master/README.md#usage

AND

https://github.com/redis-store/redis-rails#session-storage
```

**Comment by tubbo** [comment]
I've removed them so I don't have to keep dealing with this problem. What they don't know can't hurt them, right? ;-)

**Comment by sushildamdhere** [comment]
> 1) "2::23d613f35d66e1ddc5d172d382edf027237063e1506e5f50923c7285549f26ab"
127.0.0.1:6379[4]> get "2::23d613f35d66e1ddc5d172d382edf027237063e1506e5f50923c7285549f26ab"
"\x04\b{\x06I\"\x0ctesting\x06:\x06EFI\"\x1e2021-02-08 19:28:36 +0000\x06;\x00F"

@danlo by any chance, do you know what is this` "2::"` prefix here and why `session_id` is not same as what you get using `session.id`
