### ISSUE TITLE
Redis version less than 5?

### ISSUE THREAD

**Issue by drsharp** [redis-store/redis-store#349]
Version 1.9.1 still marks the `redis` dependency as `>= 4`, `< 5`. See: https://github.com/redis-store/redis-store/blob/92d4d0cf6723a560e834b8bb3bbea32f45abadcd/redis-store.gemspec#L19

That basically means only redis 4 is technically correct.

Current redis is 6.2.6:
<img width="344" alt="Screen Shot 2022-03-03 at 12 44 08 PM" src="https://user-images.githubusercontent.com/20147/156621557-499e22cf-9ac6-4d0d-bfe9-02ed3e278040.png">

Is there actually incompatibility between `redis-store:1.9.1` and redis versions >= 5? Or does this config dependency in the gemspec need to be updated?

We are in the process of a redis upgrade to support a Sidekiq upgrade but we are worried about this `< 5` dependency.

Thanks!

**Comment by tubbo** [comment]
This is the version constraint for the Redis Ruby client, which is currently still in the 4.x range.   https://github.com/redis/redis-rb/blob/master/lib/redis/version.rb
  
  
  
  
  
  

  
  
>

**Comment by drsharp** [comment]
> This is the version constraint for the Redis Ruby client, which is currently still in the 4.x range. https://github.com/redis/redis-rb/blob/master/lib/redis/version.rb

Wow, I feel a bit stupid. 🤦 I was thinking Redis version, not "redis ruby client" version.

Thank you!
