### ISSUE TITLE
Configure a CI, Travis stopped

### ISSUE THREAD

**Issue by olleolleolle** [redis-store/redis-store#350]
The current CI is not running.

<img width="948" alt="bild" src="https://user-images.githubusercontent.com/211/171339959-efef37bc-9c84-498c-9660-dcc0f9712b41.png">

- use another CI
- configure the current one in a different way

Either way, I hope we can run a CI for this repository.

**Comment by tubbo** [comment]
I've been dabbling here and there with GitHub Actions on this repo, so I think I'll move the CI stuff over to there. That said, this repo is not very active anymore so I usually tend to run all tests/linting on my own machine when merging PRs.

But the same goes for every other redis-store repo. It will definitely be a lot of work to go through each of these and update their CI configuration. Hopefully I can find one workflow that can work for all the repos.

**Comment by olleolleolle** [comment]
@tubbo Super!
