### ISSUE TITLE
Please publish a new version to rubygems 

### ISSUE THREAD

**Issue by softbrada** [redis-store/redis-store#352]
Currently in master the dependency for redis is relaxed to allow redis v5.x but the latest version is 1.9.1 which has restricted redis below version 5.x 
Can a new gem be published please? I really need redis v5.x

**Comment by tubbo** [comment]
@softbrada We're working on a quick bug that I think might preclude that release but I'll put something together this week. Shouldn't take too long. (famous last words)

**Comment by brunoqcx** [comment]
hey, upvoting  this, bundler audit is now complaining at redis-store 1.3.0 (the one from a long time ago that did not locked the redis to a maximum version) and this is causing kinda of a dependency hell for me atm  XD

**Comment by gingerlime** [comment]
Bumped into the same issue. Upgrading redis to v5 now downgrades redis-store to 1.3.0 to meet the dependency issue (1.3.0 has a more relaxed dependency on `redis >= 2.2`)

**Comment by morimorihoge** [comment]
I've got same problem caused by redis-actionpack dependency.

**Comment by gotkaren** [comment]
Same problem over here 🙏

**Comment by honkimi** [comment]
Currently, I'm setting the redis version.

gem "redis", '4.7.1'

**Comment by HarlemSquirrel** [comment]
Seems like this happened a few weeks ago https://rubygems.org/gems/redis-store/versions/1.9.1

**Comment by blerchin** [comment]
@tubbo Bumping this thread. Any possibility of a release to address this? Even a hotfix so we could have the benefit of https://github.com/redis-store/redis-store/commit/059b3188042670204ce4d8537231a70c544cc662 would be hugely helpful.

**Comment by rwojsznis** [comment]
Semi related: in case you're looking for alternative for Rails - [there is this gem](https://github.com/roidrage/redis-session-store) - it's not a drop-in replacement exactly as it uses different redis key underneath for the session storage, but I can confirm it works fine wit redis 5 (tested with a small+ size production app)

**Comment by tubbo** [comment]
@blerchin hey sorry about that, `v1.9.2` should be out momentarily addressing these issues.

@rwojsznis fwiw, that gem is only for rails session storage in particular, and this gem is the underlying library for a few other libraries, including `redis-rack-cache`.

**Comment by tubbo** [comment]
`v1.9.2` is out! closing this as completed. https://github.com/redis-store/redis-store/releases/tag/v1.9.2

**Comment by softbrada** [comment]
Thank you very much :)
