### ISSUE TITLE
Redis::Store#setnx_with_expire is broken.

### ISSUE THREAD

**Issue by hogelog** [redis-store/redis-store#353]
https://github.com/redis-store/redis-store/pull/348 breaks `Redis::Store#setnx_with_expire`.

```
          with_multi_or_pipelined(options) do |transaction|
            transaction.setnx(key, value, :raw => true)
            transaction.expire(key, ttl)
          end
```

`transaction` is `Redis` or `Redis::PipelinedConnection`, not `Redis::Store`. `:raw => true` option is invalid argument for `Redis` or `Redis::PipelinedConnection`.

## Example

```console
$ cat redis-store-setnx.rb 
require "redis-store"
Redis::Store.new.setnx("foo", 100, expire_after: 1000)
$ ruby redis-store-setnx.rb 
/Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.8.0/lib/redis/commands/strings.rb:126:in `setnx': wrong number of arguments (given 3, expected 2) (ArgumentError)
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-store-1.9.1/lib/redis/store/ttl.rb:23:in `block in setnx_with_expire'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.8.0/lib/redis.rb:227:in `block in multi'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.8.0/lib/redis.rb:265:in `block in synchronize'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.8.0/lib/redis.rb:265:in `synchronize'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-4.8.0/lib/redis.rb:222:in `multi'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-store-1.9.1/lib/redis/store/ttl.rb:38:in `with_multi_or_pipelined'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-store-1.9.1/lib/redis/store/ttl.rb:22:in `setnx_with_expire'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-store-1.9.1/lib/redis/store/ttl.rb:14:in `setnx'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-store-1.9.1/lib/redis/store/serialization.rb:9:in `block in setnx'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-store-1.9.1/lib/redis/store/serialization.rb:40:in `_marshal'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-store-1.9.1/lib/redis/store/serialization.rb:9:in `setnx'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-store-1.9.1/lib/redis/store/namespace.rb:15:in `block in setnx'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-store-1.9.1/lib/redis/store/namespace.rb:188:in `namespace'
        from /Users/hogelog/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/redis-store-1.9.1/lib/redis/store/namespace.rb:15:in `setnx'
        from redis-store-setnx.rb:2:in `<main>'
```

https://github.com/redis-store/redis-store/blob/78e382f74d8149122fce06ded24409d44f061a8b/test/redis/store_test.rb#L57-L67
also shows this defect as well.

**Comment by hogelog** [comment]
I'm working on this bug, but have not yet been able to resolve it successfully.

**Comment by tubbo** [comment]
@hogelog I think maybe we should be less permissive with the `redis` client version? https://github.com/redis-store/redis-store/blob/master/redis-store.gemspec#L19 The PR that broke this was to remove deprecated code, so what happens if you use a newer version of `redis.rb`?

**Comment by hogelog** [comment]
> I'm working on this bug, but have not yet been able to resolve it successfully.

I'm behind on this work.

> I think maybe we should be less permissive with the redis client version?

Yes, I think so too.

I checked `#setnx_with_expire` by a little script.
https://gist.github.com/hogelog/0786634452e6a2bf50e1d7e52451c72e

redis-store is not work fine with redis >= 5.

  | redis-store 1.9.0 | redis-store 1.9.1 | redis-store master | redis-store revert #348
-- | -- | -- | -- | --
redis < 4.6.0 | ok | ok | ok | ok
redis >= 4.6.0, < 5.0.0 | deprecation warning | error (this issues bug) | error (this issues bug) | deprecation warning
redis >= 5.0.0 | unsupported version | unsupported version | error (this issues bug) | no error, but not pipelined

I think it would be appropriate to revert #348 and #351 in the current implementation.
That's almost like rewinding back to 1.9.0, but I think it's appropriate to go back there once.
