### ISSUE TITLE
Error "unknown keyword: :raw" raised with Redis gem 5.x

### ISSUE THREAD

**Issue by PikachuEXE** [redis-store/redis-store#358]
Probably caused by https://github.com/redis-store/redis-store/blob/v1.9.2/lib/redis/store/factory.rb#L52

![image](https://user-images.githubusercontent.com/1018543/221463624-ac133ff3-0106-4f4c-99f7-a60663beede1.png)

Update 1: My input options:
```ruby
DEFAULT_PORT = 6379

namespace = "#{Rails.application.class.module_parent_name.underscore}:#{Rails.env.to_s.underscore}:sessions"
uri = URI.parse(Rails.configuration.redis_url)
# Rails.configuration.redis_url in development = redis://127.0.0.1:6379/0

Rails.application.config.session_store(
  :redis_store,
  redis_server: {
    host: uri.host,
    port: uri.port || DEFAULT_PORT,
    password: uri.password,
  },
  # The `key` is the cookie key name
  # The value sometimes need to be changed when rails upgraded
  # Since some values stored are classes in old rails which no longer exists
  #
  # Changing this will force all website users to be signed out
  # So only change this when necessary
  key: "_#{Rails.application.class.module_parent_name.underscore}_#{Rails.env.to_s.underscore}_sessions_#{:v2017_01_04_1426}_",
)
```

Update 2:
Tested with modified code https://github.com/PikachuEXE/redis-store/commit/50fec7055461357c4b1ddb467deb245d2d8cca0b to confirm that the error is caused by `raw` option set in this gem
Tested with development (URL mentioned above) and staging (URL like `redis://default:password@10.10.10.10:6379`)

Update 3: `raw` (in factory) introduced by https://github.com/redis-store/redis-store/pull/265

**Comment by brendo** [comment]
I can also reproduce this. It appears this is an incompatibility with `redis-rb` v5 ([CHANGELOG](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#500))

> Redis.new will now raise an error if provided unknown options.

I think a fix might be to pass `options.except(:raw, :serializer, :marshalling)` to the `super` call so that these options stay local to this gem. That's an observation, I haven't tested it yet.

**Comment by dmerand** [comment]
👋🏼 seeing the `scheme` error as well in my repo.

**Comment by nbennke** [comment]
We get `scheme` and `namespace` mentioned as unknown keywords:
```
<ArgumentError: unknown keywords: :scheme, :namespace> at
 /gems/redis-client-0.12.2/lib/redis_client/config.rb:21:in `initialize'
 /gems/redis-client-0.12.2/lib/redis_client/config.rb:182:in `initialize'
 /gems/redis-client-0.12.2/lib/redis_client.rb:143:in `new'
 /gems/redis-client-0.12.2/lib/redis_client.rb:143:in `config'
 /gems/redis-5.0.6/lib/redis/client.rb:23:in `config'
 /gems/redis-5.0.6/lib/redis.rb:157:in `initialize_client'
 /gems/redis-5.0.6/lib/redis.rb:73:in `initialize'
 /gems/redis-store-1.9.2/lib/redis/store.rb:17:in `initialize'
```

**Comment by PikachuEXE** [comment]
[`Hash#except` is only added since Ruby 3.0](https://blog.saeloun.com/2020/09/30/ruby-adds-support-for-hash-except)
Using `Hash#delete` seems fine since it's only run once per Redis instance creation
Otherwise version specific refinement might be needed (seems too complicated) or `activesupport` is needed (I rather avoid this)

**Comment by PikachuEXE** [comment]
Opened #359 but I doubt I can finish it
Help~

**Comment by DeanSingh** [comment]
Locking to `gem 'redis-store', '1.9.1'` for now get me past this issue.

**Comment by PikachuEXE** [comment]
1.9.1 cannot be used with redis 5.x - https://github.com/redis-store/redis-store/blob/v1.9.1/redis-store.gemspec
Which is the whole point of this issue

**Comment by brendo** [comment]
1.9.1 works, 1.9.2 does not.

**Comment by wbotelhos** [comment]
Thanks for the issue, @PikachuEXE .

I'm currently using a couple of incompatible keys:

```
servers: { db: 0, host: ENV.fetch('REDIS__HOST', nil), namespace: 'session', serializer: JSON },
```

The `raw` key is always added [here](https://github.com/redis-store/redis-store/blob/master/lib/redis/store/factory.rb#L52) and if you use a string, so you'll have the `schema` key and other added, so no way to get out of this issue.

**Comment by PikachuEXE** [comment]
Updated #359 but cannot solve the `mapped_mget` mystery
![image](https://user-images.githubusercontent.com/1018543/226257652-7885605e-9c79-42c1-9230-51997abe1e46.png)

**Comment by PikachuEXE** [comment]
Alright fixed the stubbing/mocking of `mapped_mget` test

**Comment by PikachuEXE** [comment]
Anyone wanna give https://github.com/redis-store/redis-store/pull/359 a try?

**Comment by rvalladares77** [comment]
I am getting this error upgrading redis-store to 1.9.2:

`ArgumentError: unknown keywords: :scheme, :namespace, :expires_in, :raw`

Settings:

Details:
Ruby 2.7.7
Rails 6.1.7
redis-rails (5.0.2)
redis (5.0.6) was (4.8.0)
redis-client (0.13.0)
redis-store (1.9.2) was (1.9.0)

**Comment by PikachuEXE** [comment]
@rvalladares77 Can you try #359 to see if that fixes the issue?

**Comment by thestephenmarshall** [comment]
@PikachuEXE I can confirm that this works for me. I am running Rails `6.0.6.1` and using `redis-actionpack` latest. 

Error was `unknown keywords: :scheme, :namespace` on initial startup first view (login). Unfortunately, the repo I am working with is private or I would share more.

I directed `redis-store` to GH on your branch like so:

`gem 'redis-store', github: 'PikachuEXE/redis-store', branch: 'fix/redis-client-compatibility'`

**Comment by PikachuEXE** [comment]
Let me ping maintainer to review that PR since we have positive feedbacks now

**Comment by digidigo** [comment]
Any update on this?  I just ran into this going through a ruby 3 upgrade since 2 EOL'd

**Comment by PikachuEXE** [comment]
Test & use #359 and maybe try to ping maintainer
I can't do anything else :S

**Comment by balbesina** [comment]
i use the following patch to bypass the issue

```ruby
class RedisClient::Config
  alias original_initialize initialize

  def initialize(**kwargs)
    # remove not supported kwargs
    original_initialize(
      **kwargs.except(:raw, :serializer, :marshalling, :namespace, :scheme)
    )
  end
end
```

**Comment by mikevoets** [comment]
Looks like the maintainer is gone from the earth :( A moment of silence please.

**Comment by lloydwatkin** [comment]
What are you doing to handle a fail due to unsupported keyword `expires_in`? A more detailed monkey patch?

**Comment by melch** [comment]
I'm also running into `initialize: unknown keyword: :raw (ArgumentError)`. There is no `raw` in our codebase.

We're using the following versions:
```
    ruby 3.2.0
    redis (5.0.7)
      redis-client (>= 0.9.0)
    redis-actionpack (5.3.0)
      actionpack (>= 5, < 8)
      redis-rack (>= 2.1.0, < 3)
      redis-store (>= 1.1.0, < 2)
    redis-activesupport (5.3.0)
      activesupport (>= 3, < 8)
      redis-store (>= 1.3, < 2)
    redis-client (0.16.0)
      connection_pool
    redis-rack (2.1.4)
      rack (>= 2.0.8, < 3)
      redis-store (>= 1.2, < 2)
    redis-rails (5.0.2)
      redis-actionpack (>= 5.0, < 6)
      redis-activesupport (>= 5.0, < 6)
      redis-store (>= 1.2, < 2)
    redis-store (1.9.2)
      redis (>= 4, < 6)
```

The monkeypatch to remove `raw` gets around it and allows the app to spin up, but I think we'll just pin an old version of redis and redis-store until this issue is fixed. If there's any more info I can include to help folks figure out where the issue is, please let me know!

**Comment by PikachuEXE** [comment]
Closing this since https://github.com/redis-store/redis-store/pull/359 merged
You can point to github (and specific commit to be sure) and see if it fixes your issue
Reopen only if more related problem found
