### ISSUE TITLE
`.to_s` breaks if the configuration defines a sentinel-based setup

### ISSUE THREAD

**Issue by slai11** [redis-store/redis-store#370]
## Issue

Some methods such as `.to_s` in `redis-store` breaks when a sentinel-based setup is used. I have a locally replicable setup (you'll need to set up a Redis with sentinels. I've a set-up [script](https://gitlab.com/schin1/redis-sentinel-setup) if that helps).

```
irb(main):001:0> require 'redis-store'
=> true
irb(main):002:0> store = ::Redis::Store::Factory.create
=> #<Redis client v5.0.8 for redis://localhost:6379/0>
irb(main):003:0> store.to_s
=> "Redis Client connected to localhost:6379 against DB 0"
irb(main):004:0> sentinel_store = ::Redis::Store::Factory.create({:password=>"password123",:name=>"mymaster", :sent
inels=>[{:host=>"localhost", :port=>26480, :password=>"password456"},{:host=>"localhost", :port=>26481, :password=>
"password456"},{:host=>"localhost", :port=>26482, :password=>"password456"}]})
=> #<Redis client v5.0.8 for redis://127.0.0.1:6480/0>
irb(main):005:0> sentinel_store.to_s
/Users/sylvesterchin/.local/share/rtx/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/redis-store-1.10.0/lib/redis/store.rb:54:in `location': undefined method `path' for #<RedisClient redis://127.0.0.1:6480/0> (NoMethodError)

      if @client.path
                ^^^^^
        from /Users/sylvesterchin/.local/share/rtx/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/redis-store-1.10.0/lib/redis/store.rb:50:in `to_s'
        from /Users/sylvesterchin/.local/share/rtx/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/redis-store-1.10.0/lib/redis/store/namespace.rb:169:in `to_s'
        from (irb):5:in `<main>'
        from /Users/sylvesterchin/.local/share/rtx/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/irb-1.7.0/exe/irb:9:in `<top (required)>'
        from /Users/sylvesterchin/.local/share/rtx/installs/ruby/3.1.4/bin/irb:25:in `load'
        from /Users/sylvesterchin/.local/share/rtx/installs/ruby/3.1.4/bin/irb:25:in `<main>'
```

## Cause

Sentinel clients uses a [different client implementation](https://github.com/redis/redis-rb/blob/2b183addb9175641a48e1d8616772282a31c0532/lib/redis/client.rb#L27) from a standalone Redis. As seen in the console output below:

```
irb(main):008:0> store.instance_variable_get(:@client)
=> #<Redis::Client redis://localhost:6379/0>
irb(main):009:0> sentinel_store.instance_variable_get(:@client)
=> #<RedisClient redis://127.0.0.1:6480/0>
```

## Workaround

For a sentinel set-up, `@client` would need to call `.config.path` instead of `.path.

Happy to help submit a patch but I'll get around to it shortly as I've other work items and this is only blocking a gem upgrade.

Note: I believe other methods which depend on `@client` are affected too. For example `.reconnect` in https://github.com/redis-store/redis-store/blob/5c3fee1b8fba672eb2bd5bfaedb973b68d12b773/lib/redis/store.rb#L46 would not work. But i'll scope this issue to sentinel-based breakages.

**Comment by PikachuEXE** [comment]
I have never used sentinel so I have no idea how to fix this :S 
Would be helpful if you can submit a PR (coz you use sentinel)

**Comment by slai11** [comment]
I've patched it in redis-client (https://github.com/redis-rb/redis-client/pull/144). Methods like `.path` are now accessible. It doesnt seem like there are any changes required here since the gemspec defines the `redis` dependency to be >=4 and < 6. A gem update would update `redis-client` to `v0.18.0` and resolve the problem.

Closing this since its resolved.

**Comment by PikachuEXE** [comment]
Good to know it's solved :)
